data:
  raw_dir: "data/raw"
  processed_dir: "data/processed"
  launch_stats_file: "launch_stats_actuals.csv"
  launch_forecast_file: "launch_forecast_actuals.csv"
  weather_hourly_file: "ccsfs_hourly_step_wx_data.csv"
  clean_launch_stats_file: "clean_launch_stats.csv"
  clean_launch_forecast_file: "clean_launch_forecast.csv"